---
title: "Secretaria Estadual de Saúde" # Título do relatório
subtitle: "**SES: Atualização dos dados do Censo 2022**"
author: "Fernanda Kelly R. Silva | www.fernandakellyrs.com"
lang: pt 
date: "`r format(Sys.Date())`" 
date-format: short 
toc: true 
format: 
    html: 
      embed-resources: true
      #css: ["custom.css"] 
      code-fold: false 
      code-tools: true  
      theme: 
        light: cosmo
        dark: superhero 
#title-block-banner: "#874a9c" 
code-annotations: hover 
execute:
  warning: false
  message: false
  echo: true
---
# Dados

## Abastecimento de água
Arquivo: ABASTECIMENTODEAGUA - Colunas: "Município";"Moradores";"Domicílios"

## Coleta de lixo
Arquivo: COLETADELIXO - Colunas: "Município";"Moradores";"Domicílios"

## Alfabetimo
Arquivo: ALFBR - Colunas:MUNCOD;ANO;CORRACA;SEXO;SITUACAO;IDADE;POPALFAB;POPNALFAB;POPTOT

## Escolaridade
Arquivo: ESCABR e ESCBBR - Colunas:MUNCOD;ANO;CORRACA;SEXO;SITUACAO;ESCOLARID;POPTOT

## População dependente
Arquivo: IDOBR - Colunas: MUNCOD;ANO;CORRACA;SEXO;IDADE;POPDEPEND;POPTOT

## Instalações sanitárias
Arquivo: INSTALACOESSANITARIAS - Colunas: Município;Moradores;Domicílios

## Renda
Arquivo: RENDBR - Colunas: MUNCOD;ANO;CORRACA;SITUACAO;NUMRENDA;DENRENDA;DENCRIREND;NUMPOBRES;NUMPOBRESX;NUMCRIPOB;NUMCRIPOBX;NUMDESOCUP;DENDESOCUP;NUMTRABINF;DENTRABINF

